In [1]:
import torch

In [2]:
# Tensor Initialization
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]],
                         dtype=torch.float32, 
                         device='cpu',
                         requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [3]:
# device
device = 'cuda' if torch.cuda.is_available() else 'cup'
my_tensor = my_tensor.to(device)

In [4]:
# important member functions
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.shape)
print(my_tensor.device)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', grad_fn=<ToCopyBackward0>)
torch.float32
torch.Size([2, 3])
cuda:0
True


In [5]:
# common initialization methods
x = torch.empty(size=(2, 2))
x = torch.zeros((3, 3))
x = torch.ones((3, 3))
x = torch.rand((3, 3))
x = torch.eye(3, 3) # Identity matrix
x = torch.arange(start=2, end=10, step=0.5) # like range function in python
x = torch.linspace(start=0, end=1, steps=30) # 30 values inbetween start and end
x = torch.empty(1, 5).normal_(mean=0, std=1) # normal distribution
x = torch.empty(1, 5).uniform_(0, 1) # uniform distribution
x = torch.diag(torch.ones(3)) # same as Identity matrix

In [6]:
# how to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor.bool()) #boolean
print(tensor.short()) #int15
print(tensor.half()) #float16
print(tensor.float()) #float32 (Important)
print(tensor.double()) #float64
print(tensor.long()) #int64 (Important)

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0, 1, 2, 3])


In [7]:
# Array to Tensor and vice versa conversion
import numpy as np
np_arr = np.array([1, 2, 3])
tensor = torch.from_numpy(np_arr)
np_arr = tensor.numpy()
print(tensor, np_arr)

tensor([1, 2, 3], dtype=torch.int32) [1 2 3]


In [8]:
#=================================================#
#         Math and Comparison Operations          #
#=================================================#
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Addition
z = x + y
z1 = torch.add(x, y)

# Subtraction
z = x - y

# Division
z = x / y

# Divide Every Element by 6
z = torch.true_divide(x, 6)

# Inplace operation
t = torch.empty(3)
t.add_(x)
t += x # both are same

# Exponentiation
z = x.pow(2)
z = x ** 2

# Simple Comparision
z = x > 0
print(z)

tensor([True, True, True])


In [9]:
# Matrix Multiplication
x1 = torch.rand((3, 5))
x2 = torch.rand((5, 3))
x3 = x1.mm(x2)
x3 = torch.mm(x1, x2)
x3 = x1 @ x2

In [10]:
# Matrix exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(2))

tensor([[1.3121, 1.5651, 0.9993, 1.1207, 0.7575],
        [1.1773, 1.1870, 0.8511, 0.9710, 0.7881],
        [0.6680, 1.0235, 1.0200, 0.7075, 0.7390],
        [1.2161, 1.5707, 1.8177, 1.0520, 1.3022],
        [0.8896, 1.4444, 1.5936, 0.8101, 1.0170]])


In [11]:
# element wise matmul
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])
c = a * b
print(c)

# dot product
c = a.dot(b)
print(c)

tensor([ 3,  8, 15])
tensor(26)


In [12]:
#=================================================#
#         Batch Matrix Multiplication             #
#=================================================#
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [17]:
#Example of broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
z = x1 - x2
z = x1 ** x2

In [78]:
#=================================================#
#      Other useful tensor Math operations        #
#=================================================#
x = torch.rand(5)
sum_x = torch.sum(x, dim=0)

values, idx = torch.max(x, dim=0)
values, idx = torch.min(x, dim=0)

abs_x = torch.abs(x)
z = torch.argmax(x)
z = torch.argmin(x)

mean_x = torch.mean(x)

z = torch.eq(x, x)

sorted_x, indices = torch.sort(x, dim=0, descending=True)

z = torch.clamp(x, min=0, max=0.5) #if the element is below 0 then it is set to 0 and above .5 then it is set to .5

In [99]:
#=================================================#
#                Tensor Indexing                  #
#=================================================#
batch_size = 10
features = 25
x = torch.rand(batch_size, features)

print(x[0, :].shape) # 

print(x[:, 0].shape)

print(x[2, 0:10].shape) # --> [0, 1, 2, ...., 9]

x[0, 0] = 100

# Fancy Indexing
x = torch.arange(10)
indices = [2, 3, 5]
x[indices]

x = torch.rand(3, 5)
rows = torch.tensor([2, 0])
cols = torch.tensor([1, 3])
x[rows, cols] # prints x[2][1] and x[0][3]

# Advanced Indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])

# Useful Operations
torch.where(x > 5, x, x*3) # if value is greater than 5 then it will be printed else it will be multiplied by 3
torch.tensor([1, 2, 3, 4, 4, 4]).unique()
torch.rand(2, 3, 3).ndimension()
torch.rand(2, 3, 3).numel() # it will print no of elements in the tensor, In this case 2*3*3

torch.Size([25])
torch.Size([10])
torch.Size([10])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


18

In [115]:
#=================================================#
#                Tensor Reshaping                 #
#=================================================#
x = torch.arange(9)

x_3x3 = x.view(3, 3) #It requires contiguous memory
print(x_3x3)
x_3x3 = x.reshape(3, 3) # so it is safe compared to view but slower

y = x_3x3.t() # transpose
print(y.contiguous().view(9))

x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

z = x1.view(-1) # it flattens
print(z.shape)

batch_size = 32
x = torch.rand(batch_size, 2, 5)
print(x.view(batch_size, -1).shape)

z = x.permute(0, 2, 1) # swap the dimensions
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1x1x10
print(x.squeeze(0).shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([32, 10])
torch.Size([32, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 10])
